POST http://localhost:3003/signup/
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmOTZiNTVhLTQxYjMtNDljYS1hNmU1LTllODlhNDRhZjcyOSIsImlhdCI6MTY3NjQwMDAzOSwiZXhwIjoxNjc2NDAzNjM5fQ.iSuRPotjVpqvzE7NLt550kKlFJ2vmy_IOu538jyOXF0

{
    "name":"Admin",
    "email":"onemore@kabum.com.br",
    "password":"123Kabum@"
}
###
GET http://localhost:3003/clients/getAll

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"admin@kabum.com.br",
    "password":"Kabum2023@"
}

###
GET http://localhost:3003/admins/getAll
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmOTZiNTVhLTQxYjMtNDljYS1hNmU1LTllODlhNDRhZjcyOSIsImlhdCI6MTY3NjQwMDAzOSwiZXhwIjoxNjc2NDAzNjM5fQ.iSuRPotjVpqvzE7NLt550kKlFJ2vmy_IOu538jyOXF0

###
DELETE http://localhost:3003/clients/delete
Content-Type: application/json
auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZmOTZiNTVhLTQxYjMtNDljYS1hNmU1LTllODlhNDRhZjcyOSIsImlhdCI6MTY3NjQwMjIzMCwiZXhwIjoxNjc2NDA1ODMwfQ.HYyom1ZoEyX-uQOXIqYYfBiBLnloKwGWeUyOkAW-PhY

{
    "cpf":"2355202200"
}