
GET http://localhost:3003/clients/getAll
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjU1MzgyMywiZXhwIjoxNjc2NTU3NDIzfQ.KfaUCFGgqOVgrnXMsLsnThwv6T5Nsrnl0NlCeR_CLyY

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"admin@kabum.com.br",
    "password":"Kabum2023@"
}

###
DELETE http://localhost:3003/clients/delete/23552202200
Content-Type: application/json
auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjU1NjA2NSwiZXhwIjoxNjc2NTU5NjY1fQ.AzHbv9vM7CNe1kdaOZaqflkN_IAhCY1LZpFCzLoxo_o


###
POST http://localhost:3003/clients/address/create
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjQ3MDc0MSwiZXhwIjoxNjc2NDc0MzQxfQ.T566EMXF4IkTxRQ8fkoi3-F9jlLq5LYrDEqfS843AeQ

{
    "cpf":"22510171194",
    "country":"Brazil",
    "state":"Rio Grande do Sul",
    "city":"Porto Alegre",
    "zipcode":"94850410",
    "full_address":"Rua edu chaves, 179 - casa 201"

}

###
GET http://localhost:3003/clients/detail
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjUwOTk1NSwiZXhwIjoxNjc2NTEzNTU1fQ.SZSkDj6v2K5z6z_GjaGvZIXaCNhp1EI7ppx_AczA0_c

{
    "cpf":"22510171194"
}

###
DELETE http://localhost:3003/clients/address/88f79c15-0df9-428a-9620-c5d51beb15a3
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0N2Y4YjU4LTk0ZDItNGQ5My1hNmMxLWU3ZTFkYTRhNTZhYyIsImlhdCI6MTY3NjQyNDE4NSwiZXhwIjoxNjc2NDI3Nzg1fQ.1J9iwK4SDRWjuk5JNX3ePYQuVw3UC4oCSgJPVxCb38Y

###
PUT http://localhost:3003/clients/update/22510171194
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjUxMjc4MywiZXhwIjoxNjc2NTE2MzgzfQ.yF08NBrzlSMvsKgswVtZm_RfC8kDPC7KEOcc4_s0TqA

{
    "rg":"1111233101",
    "name":"carlos josé"
}

###
PUT http://localhost:3003/clients/address/update/66822655-2e30-4dcc-8481-c1215dcd82c3
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjUxMjc4MywiZXhwIjoxNjc2NTE2MzgzfQ.yF08NBrzlSMvsKgswVtZm_RfC8kDPC7KEOcc4_s0TqA

{
    "full_address":"Rua trevo, 182"
}

###
GET http://localhost:3003/clients/address/22510171194
auth:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjUxNDkwMywiZXhwIjoxNjc2NTE4NTAzfQ.wYdSW0A3eYxchZEdYj2K7pD-lmsHvNggfPfu_WmPL2c

###
POST  http://localhost:3003/clients/create
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5MjQxNWE3LTQwNjctNDFiZi05ODk3LTJjYjBkOWZkMjkzMyIsImlhdCI6MTY3NjUyMjU2OCwiZXhwIjoxNjc2NTI2MTY4fQ.Oh3Ni0q9izriyrLx34RCm4uyFAOehw0buu8Jpc-ompw

{
    "name":"Carlos Alberto",
    "cpf":"03333995045",
    "rg":"1111233154",
    "birthdate":"1994-09-05",
    "phone":"1132459520"
}
